## This is basic continuous integration build for your Quarkus application.

name: Quarkus Codestart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  secrets:
    name: check secrets
    runs-on: ubuntu-20.04
    outputs:
      available: ${{ steps.secrets.outputs.available }}
    steps:
      - name: Check whether OpenShift requests should be done
        id: secrets
        env:
          secretsavailable: ${{ secrets.OPENSHIFT_SERVER_URL != '' && secrets.OPENSHIFT_TOKEN != '' && github.event.pull_request == '' }}
        run: |
          echo "available: ${{ env.secretsavailable }}"
          echo "::set-output name=available::${{ env.secretsavailable }}"

  build:
    needs: secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: |
          ./mvnw -B verify
      - name: Authenticate and set context
        if: ${{ needs.secrets.outputs.available }}
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      - name: Deploy
        if: ${{ needs.secrets.outputs.available }}
        run: |
          ./mvnw -B verify -DskipTests -Dquarkus.kubernetes.deploy=true -Dquarkus.kubernetes.expose=true


